//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IAtCashAccountAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/8/11 19:50:50
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IAtCashAccountAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.AtCashAccount Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.AtCashAccount e);
		
		void Update(Model.AtCashAccount e);
		
		IList<Model.AtCashAccount> Select();
		
		IList<Model.AtCashAccount> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.AtCashAccount e);
		
		bool HasRowsAfter(Model.AtCashAccount e);
		
		Model.AtCashAccount GetFirst();
		
		Model.AtCashAccount GetLast();
		
		Model.AtCashAccount GetPrev(Model.AtCashAccount e);
		
		Model.AtCashAccount GetNext(Model.AtCashAccount e);

	}
}
