//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IAtCashAccountDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/8/11 19:50:50
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IAtCashAccountDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.AtCashAccountDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.AtCashAccountDetail e);
		
		void Update(Model.AtCashAccountDetail e);
		
		IList<Model.AtCashAccountDetail> Select();
		
		IList<Model.AtCashAccountDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
