//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IShouldPayAccountConditionAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/11/19 18:29:36
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IShouldPayAccountConditionAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.ShouldPayAccountCondition Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.ShouldPayAccountCondition e);
		
		void Update(Model.ShouldPayAccountCondition e);
		
		IList<Model.ShouldPayAccountCondition> Select();
		
		IList<Model.ShouldPayAccountCondition> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
