//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IShouldPayAccountDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/11/5 22:26:46
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IShouldPayAccountDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.ShouldPayAccountDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.ShouldPayAccountDetail e);
		
		void Update(Model.ShouldPayAccountDetail e);
		
		IList<Model.ShouldPayAccountDetail> Select();
		
		IList<Model.ShouldPayAccountDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.ShouldPayAccountDetail e);
		
		bool HasRowsAfter(Model.ShouldPayAccountDetail e);
		
		Model.ShouldPayAccountDetail GetFirst();
		
		Model.ShouldPayAccountDetail GetLast();
		
		Model.ShouldPayAccountDetail GetPrev(Model.ShouldPayAccountDetail e);
		
		Model.ShouldPayAccountDetail GetNext(Model.ShouldPayAccountDetail e);

	}
}
