//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AtCashAccountAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/8/11 19:50:50
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class AtCashAccountAccessor
    {
		public Model.AtCashAccount Get(string id)
		{
			return this.Get<Model.AtCashAccount>(id);
		}
		
		public void Insert(Model.AtCashAccount e)
		{
			this.Insert<Model.AtCashAccount>(e);
		}
		
		public void Update(Model.AtCashAccount e)
		{
			this.Update<Model.AtCashAccount>(e);
		}
		
		public IList<Model.AtCashAccount> Select()
		{
			return this.Select<Model.AtCashAccount>();
		}
		
		public IList<Model.AtCashAccount> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.AtCashAccount>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.AtCashAccount>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.AtCashAccount>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.AtCashAccount>();
		}
		public int Count()
		{
			return this.Count<Model.AtCashAccount>();
		}
		public bool HasRowsBefore(Model.AtCashAccount e)
		{
			return sqlmapper.QueryForObject<bool>("AtCashAccount.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.AtCashAccount e)
		{
			return sqlmapper.QueryForObject<bool>("AtCashAccount.has_rows_after", e);
		}
		public Model.AtCashAccount GetFirst()
		{
			return sqlmapper.QueryForObject<Model.AtCashAccount>("AtCashAccount.get_first", null);
		}
		public Model.AtCashAccount GetLast()
		{
			return sqlmapper.QueryForObject<Model.AtCashAccount>("AtCashAccount.get_last", null);
		}
		public Model.AtCashAccount GetNext(Model.AtCashAccount e)
		{
			return sqlmapper.QueryForObject<Model.AtCashAccount>("AtCashAccount.get_next", e);
		}
		public Model.AtCashAccount GetPrev(Model.AtCashAccount e)
		{
			return sqlmapper.QueryForObject<Model.AtCashAccount>("AtCashAccount.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("AtCashAccount.existsPrimary", id);
		}
    }
}
