//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AtCashAccountDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/8/11 19:50:50
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class AtCashAccountDetailAccessor
    {
		public Model.AtCashAccountDetail Get(string id)
		{
			return this.Get<Model.AtCashAccountDetail>(id);
		}
		
		public void Insert(Model.AtCashAccountDetail e)
		{
			this.Insert<Model.AtCashAccountDetail>(e);
		}
		
		public void Update(Model.AtCashAccountDetail e)
		{
			this.Update<Model.AtCashAccountDetail>(e);
		}
		
		public IList<Model.AtCashAccountDetail> Select()
		{
			return this.Select<Model.AtCashAccountDetail>();
		}
		
		public IList<Model.AtCashAccountDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.AtCashAccountDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.AtCashAccountDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.AtCashAccountDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.AtCashAccountDetail>();
		}
		public int Count()
		{
			return this.Count<Model.AtCashAccountDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("AtCashAccountDetail.existsPrimary", id);
		}
    }
}
