//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ShouldPayAccountDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/11/5 22:26:47
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class ShouldPayAccountDetailAccessor
    {
		public Model.ShouldPayAccountDetail Get(string id)
		{
			return this.Get<Model.ShouldPayAccountDetail>(id);
		}
		
		public void Insert(Model.ShouldPayAccountDetail e)
		{
			this.Insert<Model.ShouldPayAccountDetail>(e);
		}
		
		public void Update(Model.ShouldPayAccountDetail e)
		{
			this.Update<Model.ShouldPayAccountDetail>(e);
		}
		
		public IList<Model.ShouldPayAccountDetail> Select()
		{
			return this.Select<Model.ShouldPayAccountDetail>();
		}
		
		public IList<Model.ShouldPayAccountDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.ShouldPayAccountDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.ShouldPayAccountDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.ShouldPayAccountDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.ShouldPayAccountDetail>();
		}
		public int Count()
		{
			return this.Count<Model.ShouldPayAccountDetail>();
		}
		public bool HasRowsBefore(Model.ShouldPayAccountDetail e)
		{
			return sqlmapper.QueryForObject<bool>("ShouldPayAccountDetail.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.ShouldPayAccountDetail e)
		{
			return sqlmapper.QueryForObject<bool>("ShouldPayAccountDetail.has_rows_after", e);
		}
		public Model.ShouldPayAccountDetail GetFirst()
		{
			return sqlmapper.QueryForObject<Model.ShouldPayAccountDetail>("ShouldPayAccountDetail.get_first", null);
		}
		public Model.ShouldPayAccountDetail GetLast()
		{
			return sqlmapper.QueryForObject<Model.ShouldPayAccountDetail>("ShouldPayAccountDetail.get_last", null);
		}
		public Model.ShouldPayAccountDetail GetNext(Model.ShouldPayAccountDetail e)
		{
			return sqlmapper.QueryForObject<Model.ShouldPayAccountDetail>("ShouldPayAccountDetail.get_next", e);
		}
		public Model.ShouldPayAccountDetail GetPrev(Model.ShouldPayAccountDetail e)
		{
			return sqlmapper.QueryForObject<Model.ShouldPayAccountDetail>("ShouldPayAccountDetail.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("ShouldPayAccountDetail.existsPrimary", id);
		}
    }
}
