//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ShouldPayAccountConditionAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/11/19 18:29:36
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class ShouldPayAccountConditionAccessor
    {
		public Model.ShouldPayAccountCondition Get(string id)
		{
			return this.Get<Model.ShouldPayAccountCondition>(id);
		}
		
		public void Insert(Model.ShouldPayAccountCondition e)
		{
			this.Insert<Model.ShouldPayAccountCondition>(e);
		}
		
		public void Update(Model.ShouldPayAccountCondition e)
		{
			this.Update<Model.ShouldPayAccountCondition>(e);
		}
		
		public IList<Model.ShouldPayAccountCondition> Select()
		{
			return this.Select<Model.ShouldPayAccountCondition>();
		}
		
		public IList<Model.ShouldPayAccountCondition> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.ShouldPayAccountCondition>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.ShouldPayAccountCondition>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.ShouldPayAccountCondition>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.ShouldPayAccountCondition>();
		}
		public int Count()
		{
			return this.Count<Model.ShouldPayAccountCondition>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("ShouldPayAccountCondition.existsPrimary", id);
		}
    }
}
