//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AtCashAccountManager.autogenerated.cs
// author: mayanjun
// create date：2014/8/11 19:50:50
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class AtCashAccountManager
    {
		///<summary>
		/// Data accessor of dbo.AtCashAccount
		///</summary>
		private static readonly DA.IAtCashAccountAccessor accessor = (DA.IAtCashAccountAccessor)Accessors.Get("AtCashAccountAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.AtCashAccount Get(string atCashAccountId)
		{
			return accessor.Get(atCashAccountId);
		}
		
		public bool HasRows(string atCashAccountId)
		{
			return accessor.HasRows(atCashAccountId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.AtCashAccount e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.AtCashAccount e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.AtCashAccount GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.AtCashAccount GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.AtCashAccount GetPrev(Model.AtCashAccount e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.AtCashAccount GetNext(Model.AtCashAccount e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.AtCashAccount> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.AtCashAccount> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
