//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ShouldPayAccountDetailManager.autogenerated.cs
// author: mayanjun
// create date：2014/11/5 22:26:47
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ShouldPayAccountDetailManager
    {
		///<summary>
		/// Data accessor of dbo.ShouldPayAccountDetail
		///</summary>
		private static readonly DA.IShouldPayAccountDetailAccessor accessor = (DA.IShouldPayAccountDetailAccessor)Accessors.Get("ShouldPayAccountDetailAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ShouldPayAccountDetail Get(string shouldPayAccountDetailId)
		{
			return accessor.Get(shouldPayAccountDetailId);
		}
		
		public bool HasRows(string shouldPayAccountDetailId)
		{
			return accessor.HasRows(shouldPayAccountDetailId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.ShouldPayAccountDetail e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.ShouldPayAccountDetail e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.ShouldPayAccountDetail GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.ShouldPayAccountDetail GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.ShouldPayAccountDetail GetPrev(Model.ShouldPayAccountDetail e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.ShouldPayAccountDetail GetNext(Model.ShouldPayAccountDetail e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ShouldPayAccountDetail> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ShouldPayAccountDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
