//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ShouldPayAccountConditionManager.autogenerated.cs
// author: mayanjun
// create date：2014/11/19 18:29:36
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ShouldPayAccountConditionManager
    {
		///<summary>
		/// Data accessor of dbo.ShouldPayAccountCondition
		///</summary>
		private static readonly DA.IShouldPayAccountConditionAccessor accessor = (DA.IShouldPayAccountConditionAccessor)Accessors.Get("ShouldPayAccountConditionAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ShouldPayAccountCondition Get(string shouldPayAccountConditionId)
		{
			return accessor.Get(shouldPayAccountConditionId);
		}
		
		public bool HasRows(string shouldPayAccountConditionId)
		{
			return accessor.HasRows(shouldPayAccountConditionId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ShouldPayAccountCondition> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ShouldPayAccountCondition> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
