//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ShouldPayAccountManager.autogenerated.cs
// author: mayanjun
// create date：2014/8/11 19:47:22
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ShouldPayAccountManager
    {
		///<summary>
		/// Data accessor of dbo.ShouldPayAccount
		///</summary>
		private static readonly DA.IShouldPayAccountAccessor accessor = (DA.IShouldPayAccountAccessor)Accessors.Get("ShouldPayAccountAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ShouldPayAccount Get(string shouldPayAccountId)
		{
			return accessor.Get(shouldPayAccountId);
		}
		
		public bool HasRows(string shouldPayAccountId)
		{
			return accessor.HasRows(shouldPayAccountId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.ShouldPayAccount e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.ShouldPayAccount e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.ShouldPayAccount GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.ShouldPayAccount GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.ShouldPayAccount GetPrev(Model.ShouldPayAccount e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.ShouldPayAccount GetNext(Model.ShouldPayAccount e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ShouldPayAccount> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ShouldPayAccount> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
