//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AtCashAccount.autogenerated.cs
// author: mayanjun
// create date：2014/8/11 19:50:50
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class AtCashAccount
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _atCashAccountId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _atCashAccountMonth;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _incomeTotal;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _payTotal;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _balanceTotal;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string AtCashAccountId
		{
			get 
			{
				return this._atCashAccountId;
			}
			set 
			{
				this._atCashAccountId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? AtCashAccountMonth
		{
			get 
			{
				return this._atCashAccountMonth;
			}
			set 
			{
				this._atCashAccountMonth = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? IncomeTotal
		{
			get 
			{
				return this._incomeTotal;
			}
			set 
			{
				this._incomeTotal = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? PayTotal
		{
			get 
			{
				return this._payTotal;
			}
			set 
			{
				this._payTotal = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? BalanceTotal
		{
			get 
			{
				return this._balanceTotal;
			}
			set 
			{
				this._balanceTotal = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_AtCashAccountId = "AtCashAccountId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_AtCashAccountMonth = "AtCashAccountMonth";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_IncomeTotal = "IncomeTotal";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PayTotal = "PayTotal";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_BalanceTotal = "BalanceTotal";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		

		#endregion
	}
}