//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCDoubleImpactCheckDetail.autogenerated.cs
// author: mayanjun
// create date：2011-11-24 17:38:51
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class PCDoubleImpactCheckDetail
    {
        #region Data

        /// <summary>
        /// 
        /// </summary>
        private string _pCDoubleImpactCheckDetailID;

        /// <summary>
        /// 
        /// </summary>
        private string _pCDoubleImpactCheckID;

        /// <summary>
        /// 
        /// </summary>
        private string _employeeId;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _pCDoubleImpactCheckDetailDate;

        /// <summary>
        /// 
        /// </summary>
        private string _pCDoubleImpactCheckBanBie;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJiaoLianL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJiaoLianR;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPUpL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPUpR;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPDownL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPDownR;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPLeftL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPLeftR;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPRightL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPRightR;

        /// <summary>
        /// 
        /// </summary>
        private string _attrBiZhong;

        /// <summary>
        /// 
        /// </summary>
        private string _attrShangLiangL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrShangLiangR;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPZYL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrJPZYR;

        /// <summary>
        /// 
        /// </summary>
        private string _attrS_SZhongL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrS_SZhongR;

        /// <summary>
        /// 
        /// </summary>
        private string _attrS_SShangL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrS_SShangR;

        /// <summary>
        /// 
        /// </summary>
        private string _attrS_SXiaL;

        /// <summary>
        /// 
        /// </summary>
        private string _attrS_SXiaR;

        private string _attrHeat60;

        private string _attrHeat30m;

        /// <summary>
        /// ANSI~CSA/H.M冲击测试单
        /// </summary>
        private PCDoubleImpactCheck _pCDoubleImpactCheck;
        /// <summary>
        /// 员工
        /// </summary>
        private Employee _employee;

        #endregion

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string PCDoubleImpactCheckDetailID
        {
            get
            {
                return this._pCDoubleImpactCheckDetailID;
            }
            set
            {
                this._pCDoubleImpactCheckDetailID = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string PCDoubleImpactCheckID
        {
            get
            {
                return this._pCDoubleImpactCheckID;
            }
            set
            {
                this._pCDoubleImpactCheckID = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string EmployeeId
        {
            get
            {
                return this._employeeId;
            }
            set
            {
                this._employeeId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? PCDoubleImpactCheckDetailDate
        {
            get
            {
                return this._pCDoubleImpactCheckDetailDate;
            }
            set
            {
                this._pCDoubleImpactCheckDetailDate = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string PCDoubleImpactCheckBanBie
        {
            get
            {
                return this._pCDoubleImpactCheckBanBie;
            }
            set
            {
                this._pCDoubleImpactCheckBanBie = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJiaoLianL
        {
            get
            {
                return this._attrJiaoLianL;
            }
            set
            {
                this._attrJiaoLianL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJiaoLianR
        {
            get
            {
                return this._attrJiaoLianR;
            }
            set
            {
                this._attrJiaoLianR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPUpL
        {
            get
            {
                return this._attrJPUpL;
            }
            set
            {
                this._attrJPUpL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPUpR
        {
            get
            {
                return this._attrJPUpR;
            }
            set
            {
                this._attrJPUpR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPDownL
        {
            get
            {
                return this._attrJPDownL;
            }
            set
            {
                this._attrJPDownL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPDownR
        {
            get
            {
                return this._attrJPDownR;
            }
            set
            {
                this._attrJPDownR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPLeftL
        {
            get
            {
                return this._attrJPLeftL;
            }
            set
            {
                this._attrJPLeftL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPLeftR
        {
            get
            {
                return this._attrJPLeftR;
            }
            set
            {
                this._attrJPLeftR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPRightL
        {
            get
            {
                return this._attrJPRightL;
            }
            set
            {
                this._attrJPRightL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPRightR
        {
            get
            {
                return this._attrJPRightR;
            }
            set
            {
                this._attrJPRightR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrBiZhong
        {
            get
            {
                return this._attrBiZhong;
            }
            set
            {
                this._attrBiZhong = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrShangLiangL
        {
            get
            {
                return this._attrShangLiangL;
            }
            set
            {
                this._attrShangLiangL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrShangLiangR
        {
            get
            {
                return this._attrShangLiangR;
            }
            set
            {
                this._attrShangLiangR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPZYL
        {
            get
            {
                return this._attrJPZYL;
            }
            set
            {
                this._attrJPZYL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrJPZYR
        {
            get
            {
                return this._attrJPZYR;
            }
            set
            {
                this._attrJPZYR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrS_SZhongL
        {
            get
            {
                return this._attrS_SZhongL;
            }
            set
            {
                this._attrS_SZhongL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrS_SZhongR
        {
            get
            {
                return this._attrS_SZhongR;
            }
            set
            {
                this._attrS_SZhongR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrS_SShangL
        {
            get
            {
                return this._attrS_SShangL;
            }
            set
            {
                this._attrS_SShangL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrS_SShangR
        {
            get
            {
                return this._attrS_SShangR;
            }
            set
            {
                this._attrS_SShangR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrS_SXiaL
        {
            get
            {
                return this._attrS_SXiaL;
            }
            set
            {
                this._attrS_SXiaL = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string attrS_SXiaR
        {
            get
            {
                return this._attrS_SXiaR;
            }
            set
            {
                this._attrS_SXiaR = value;
            }
        }

        public string attrHeat60
        {
            get { return _attrHeat60; }
            set { _attrHeat60 = value; }
        }

        public string attrHeat30m
        {
            get { return _attrHeat30m; }
            set { _attrHeat30m = value; }
        }

        /// <summary>
        /// ANSI~CSA/H.M冲击测试单
        /// </summary>
        public virtual PCDoubleImpactCheck PCDoubleImpactCheck
        {
            get
            {
                return this._pCDoubleImpactCheck;
            }
            set
            {
                this._pCDoubleImpactCheck = value;
            }

        }
        /// <summary>
        /// 员工
        /// </summary>
        public virtual Employee Employee
        {
            get
            {
                return this._employee;
            }
            set
            {
                this._employee = value;
            }

        }
        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDoubleImpactCheckDetailID = "PCDoubleImpactCheckDetailID";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDoubleImpactCheckID = "PCDoubleImpactCheckID";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_EmployeeId = "EmployeeId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDoubleImpactCheckDetailDate = "PCDoubleImpactCheckDetailDate";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDoubleImpactCheckBanBie = "PCDoubleImpactCheckBanBie";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJiaoLianL = "attrJiaoLianL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJiaoLianR = "attrJiaoLianR";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPUpL = "attrJPUpL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPUpR = "attrJPUpR";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPDownL = "attrJPDownL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPDownR = "attrJPDownR";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPLeftL = "attrJPLeftL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPLeftR = "attrJPLeftR";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPRightL = "attrJPRightL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPRightR = "attrJPRightR";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrBiZhong = "attrBiZhong";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrShangLiangL = "attrShangLiangL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrShangLiangR = "attrShangLiangR";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPZYL = "attrJPZYL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrJPZYR = "attrJPZYR";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrS_SZhongL = "attrS_SZhongL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrS_SZhongR = "attrS_SZhongR";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrS_SShangL = "attrS_SShangL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrS_SShangR = "attrS_SShangR";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrS_SXiaL = "attrS_SXiaL";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_attrS_SXiaR = "attrS_SXiaR";

        public readonly static string PRO_attrHeat60 = "attrHeat60";

        public readonly static string PRO_attrHeat30m = "attrHeat30m";

        #endregion
    }
}
