//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ShouldPayAccountCondition.autogenerated.cs
// author: mayanjun
// create date：2014/11/19 18:29:36
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ShouldPayAccountCondition
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _shouldPayAccountConditionId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _startInvoiceDate;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _endInvoiceDate;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _startJHDate;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _endJHDate;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _startFKDate;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _endFKDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _supplierStartId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _supplierEndId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productStartId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productEndId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _cOStartId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _cOEndId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _cusXOId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _empStartId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _empEndId;
		
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _empEnd;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _empStart;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _productEnd;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _productStart;
		/// <summary>
		/// 供应商
		/// </summary>
		private Supplier _supplierEnd;
		/// <summary>
		/// 供应商
		/// </summary>
		private Supplier _supplierStart;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string ShouldPayAccountConditionId
		{
			get 
			{
				return this._shouldPayAccountConditionId;
			}
			set 
			{
				this._shouldPayAccountConditionId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? StartInvoiceDate
		{
			get 
			{
				return this._startInvoiceDate;
			}
			set 
			{
				this._startInvoiceDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? EndInvoiceDate
		{
			get 
			{
				return this._endInvoiceDate;
			}
			set 
			{
				this._endInvoiceDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? StartJHDate
		{
			get 
			{
				return this._startJHDate;
			}
			set 
			{
				this._startJHDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? EndJHDate
		{
			get 
			{
				return this._endJHDate;
			}
			set 
			{
				this._endJHDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? StartFKDate
		{
			get 
			{
				return this._startFKDate;
			}
			set 
			{
				this._startFKDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? EndFKDate
		{
			get 
			{
				return this._endFKDate;
			}
			set 
			{
				this._endFKDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string SupplierStartId
		{
			get 
			{
				return this._supplierStartId;
			}
			set 
			{
				this._supplierStartId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string SupplierEndId
		{
			get 
			{
				return this._supplierEndId;
			}
			set 
			{
				this._supplierEndId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductStartId
		{
			get 
			{
				return this._productStartId;
			}
			set 
			{
				this._productStartId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductEndId
		{
			get 
			{
				return this._productEndId;
			}
			set 
			{
				this._productEndId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string COStartId
		{
			get 
			{
				return this._cOStartId;
			}
			set 
			{
				this._cOStartId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string COEndId
		{
			get 
			{
				return this._cOEndId;
			}
			set 
			{
				this._cOEndId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string CusXOId
		{
			get 
			{
				return this._cusXOId;
			}
			set 
			{
				this._cusXOId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmpStartId
		{
			get 
			{
				return this._empStartId;
			}
			set 
			{
				this._empStartId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmpEndId
		{
			get 
			{
				return this._empEndId;
			}
			set 
			{
				this._empEndId = value;
			}
		}
	
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee EmpEnd
		{
			get
			{
				return this._empEnd;
			}
			set
			{
				this._empEnd = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee EmpStart
		{
			get
			{
				return this._empStart;
			}
			set
			{
				this._empStart = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product ProductEnd
		{
			get
			{
				return this._productEnd;
			}
			set
			{
				this._productEnd = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product ProductStart
		{
			get
			{
				return this._productStart;
			}
			set
			{
				this._productStart = value;
			}
			
		}
		/// <summary>
		/// 供应商
		/// </summary>
		public virtual Supplier SupplierEnd
		{
			get
			{
				return this._supplierEnd;
			}
			set
			{
				this._supplierEnd = value;
			}
			
		}
		/// <summary>
		/// 供应商
		/// </summary>
		public virtual Supplier SupplierStart
		{
			get
			{
				return this._supplierStart;
			}
			set
			{
				this._supplierStart = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ShouldPayAccountConditionId = "ShouldPayAccountConditionId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_StartInvoiceDate = "StartInvoiceDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EndInvoiceDate = "EndInvoiceDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_StartJHDate = "StartJHDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EndJHDate = "EndJHDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_StartFKDate = "StartFKDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EndFKDate = "EndFKDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_SupplierStartId = "SupplierStartId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_SupplierEndId = "SupplierEndId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductStartId = "ProductStartId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductEndId = "ProductEndId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_COStartId = "COStartId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_COEndId = "COEndId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_CusXOId = "CusXOId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmpStartId = "EmpStartId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmpEndId = "EmpEndId";
		

		#endregion
	}
}